name: pkgindex test

on:
  push:
    branches:
      - '**'
    paths:
      - 'pkgs/**'

jobs:

  linux-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Installation Xlings on Ubuntu
        run: curl -fsSL https://d2learn.org/xlings-install.sh | bash

      - name: Get changed-files (only pull_request）
        uses: tj-actions/changed-files@v46
        id: changed-files
        with:
          path: pkgs/

      - name: Package File Test
        run: |
          source ~/.bashrc
          export PATH=/home/xlings/.xlings_data/bin:$PATH
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "---"
            output=$(xim --add-xpkg "pkgs/$file" 2>&1)
            echo "$output"
            if echo "$output" | grep -i "error"; then
              echo "❌ Error detected in $file"
              exit 1
            fi
          done