# .github/workflows/pkgindex-deploy.yml

name: Deploy PkgIndex Site

on:
  push:
    branches:
      - main
    paths:
      - 'pkgs/**'

  # Manual trigger for deployment
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取xpkgindex索引站点生成工具
      - name: Checkout repository xpkgindex
        uses: actions/checkout@v3
        with:
          repository: d2learn/xpkgindex
          path: xpkgindex

      # 2. 拉取包索引仓库
      - name: Clone xim-pkgindex into subdirectory
        run: |
          git clone --depth=1 https://github.com/d2learn/xim-pkgindex.git xpkgindex/xim-pkgindex

      # 3. 安装xlings
      - name: Installation Xlings on Ubuntu
        run: curl -fsSL https://d2learn.org/xlings-install.sh | bash

      # 4. 生成索引站点
      - name: Generate static site
        run: |
          source ~/.bashrc
          export PATH=/home/xlings/.xlings_data/bin:$PATH
          cd xpkgindex
          python3 -m pip install -r requirements.txt
          python3 src/xpkgindex.py xim-pkgindex/pkgs

      # 5. 上传生成的索引站点
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./xpkgindex/site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4